<?php
//session_start();
require('include.php');
//if(@$_SESSION["username"])
?>
<?php include('header.php');
?>
<div id="container">
<table width="100%">
<tr>
<td width="5%"></td>
<td bgcolor="White" width="17%">
<img src="images/1499.jpg" height=230 width=250></a>
</td>
<td width=".5%"></td>
<td bgcolor="Grey" width="20%" valign=top>
<font face="Calibri" size="5" color="yellow">
<ul type="square">
<li><b><font face="Calibri" size="3" color="white">.can accomodate board mebers</b>
<li><b><font face="Calibri" size="3" color="orange"> .can accomodate board mebers</b>
<li><b><font face="Calibri" size="3" color="blue">You will not need to worry about your customers comfort!</b>
<li><b><font face="Calibri" size="4" color="black">Price:</b>Ksh15,000
</ul>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <a href="orderdetails.php"><input type="button" value="Book Now!"></a>
</td>
<td width="5%"></td>
<td bgcolor="White" width="17%">
<img src="images/image.jpg" height=230 width=250></a>
</td>
<td width=".5%"></td>
<td bgcolor="Grey" width="20%" valign=top>
<font face="Calibri" size="5" color="yellow">
<ul type="square">
<li><b><font face="Calibri" size="3" color="white"> can accomodate board mebers/b>
<li><b><font face="Calibri" size="3" color="orange">You will not need to worry about your customers comfort!</b>
<li><b><font face="Calibri" size="3" color="blue">Its low height enhances its beauty and functionality </b>
<li><b><font face="Calibri" size="4" color="black">Price:</b>Ksh15,000 per hr
</ul>
<br>
<br>
<br>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <a href="orderdetails.php"><input type="button" value="Book Now!"></a>
</td>
<td width="12%"></td>
</tr>
</table>
<br>
<hr align=center color="yellow" size=3.5 width="100%" noshade>
<br>
<table width="100%">
<tr>
<td width="5%"></td>
<td bgcolor="White" width="17%">
<img src="images/129.png.jpg" height=230 width=250></a>
</td>
<td width=".5%"></td>
<td bgcolor="Grey" width="20%" valign=top>
<font face="Calibri" size="5" color="yellow">
<ul type="square">
<li><b><font face="Calibri" size="3" color="white">Description: ladies We know you love colour ,this bright earth coloured single sofa is beautiful .</b>
<li><b><font face="Calibri" size="3" color="orange">.You will not need to worry about your customers comfort!</b>
<li><b><font face="Calibri" size="3" color="blue">different colors </b>
<li><b><font face="Calibri" size="4" color="black">Price:</b>Ksh 15,000 per hour
</ul>
<br>
<br>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <a href="orderdetails.php"><input type="button" value="Book Now!"></a>
</td>
<td width="5%"></td>
<td bgcolor="White" width="17%">
<img src="images/91.png.jpg" height=230 width=250></a>
</td>
<td width=".5%"></td>
<td bgcolor="Grey" width="20%" valign=top>
<font face="Calibri" size="5" color="yellow">
<ul type="square">
<li><b><font face="Calibri" size="3" color="white">You will not need to worry about your customers comfort!,</b>
<li><b><font face="Calibri" size="3" color="orange">You will not need to worry about your customers comfort!</b>
<li><b><font face="Calibri" size="3" color="blue">You will not need to worry about your customers comfort!</b>
<li><b><font face="Calibri" size="4" color="black">Price:</b>Ksh15,000 per hour
</ul>
<br>
<br>
<br>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <a href="orderdetails.php"><input type="button" value="Book Now!"></a>
</td>
<td width="12%"></td>
</tr>
</table>
<br>
<hr align=center color="yellow" size=3.5 width="100%" noshade>
<br>
<table width="100%">
<tr>
<td width="5%"></td>
<td bgcolor="White" width="17%">
<img src="images/123456.jpg" height=230 width=250></a>
</td>
<td width=".5%"></td>
<td bgcolor="Grey" width="20%" valign=top>
<font face="Calibri" size="5" color="yellow">
<ul type="square">
<li><b><font face="Calibri" size="3" color="white">Description:Executive Table</b>
<li><b><font face="Calibri" size="3" color="orange"></b>
<li><b><font face="Calibri" size="3" color="blue"> </b>
<li><b><font face="Calibri" size="4" color="black">Price:</b>Ksh 15,000 per hour.
</ul>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <a href="orderdetails.php"><input type="button" value="Book Now!"></a>
</td>
<td width="5%"></td>
<td bgcolor="White" width="17%">
<img src="images/1234.jpg" height=230 width=250></a>
</td>
<td width=".5%"></td>
<td bgcolor="Grey" width="20%" valign=top>
<font face="Calibri" size="5" color="yellow">
<ul type="square">
<li><b><font face="Calibri" size="3" color="white">You will not need to worry about your customers comfort!</b>
<li><b><font face="Calibri" size="3" color="orange">Executive Table</b>
<li><b><font face="Calibri" size="3" color="blue">Executive Table</b>
<li><b><font face="Calibri" size="4" color="black">Price:</b>Ksh 15,000 per hour
</ul>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <a href="orderdetails.php"><input type="button" value="Book Now!"></a>
</td>
<td width="12%"></td>
</tr>
</table>	
</div>
<?php include('footer.php');
?>